language: php

php:
    - 5.4
    - 5.5
    - 5.6
    - 7.0
    - hhvm

matrix:
    allow_failures:
        - php: hhvm

before_script:
    # Update composer
    - composer self-update

    # Install Nette Tester
    - composer install --no-interaction --dev --prefer-source

script: vendor/bin/tester -p php -s tests

after_failure:
    # Print *.actual content
    - for i in $(find tests -name \*.actual); do echo "--- $i"; cat $i; echo; echo; done
